#!/bin/bash
set -e

# ============================================
# Japan REIT - Vultr VPS Deploy Script
# ============================================
# Run this on a fresh Ubuntu 22.04/24.04 VPS:
#   curl -fsSL https://raw.githubusercontent.com/<your-repo>/main/deploy.sh | bash
#   OR: ssh into VPS, clone repo, run: bash deploy.sh

echo "=========================================="
echo "  Japan REIT - Production Deployment"
echo "=========================================="

# --- 1. Install Docker ---
if ! command -v docker &> /dev/null; then
    echo "[1/5] Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    echo "[1/5] Docker installed."
else
    echo "[1/5] Docker already installed, skipping."
fi

# --- 2. Setup project directory ---
APP_DIR="/opt/japan-reit"
echo "[2/5] Setting up project directory at $APP_DIR..."

if [ ! -d "$APP_DIR" ]; then
    # If running from the repo directory, copy everything
    if [ -f "docker-compose.prod.yml" ]; then
        cp -r "$(pwd)" "$APP_DIR"
    else
        echo "ERROR: Run this script from the project root (where docker-compose.prod.yml is)"
        echo "OR clone the repo first: git clone <your-repo> $APP_DIR"
        exit 1
    fi
fi
cd "$APP_DIR"

# --- 3. Generate production .env ---
ENV_FILE="$APP_DIR/.env.production"
if [ ! -f "$ENV_FILE" ] || grep -q "CHANGE_ME" "$ENV_FILE"; then
    echo "[3/5] Generating production environment..."
    DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh on $(date -Iseconds)
POSTGRES_USER=japan_reit
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=japan_reit
REINFOLIB_API_KEY=${REINFOLIB_API_KEY:-}
SCHEDULER_ENABLED=true
SCHEDULER_INTERVAL_HOURS=6
APP_PORT=80
EOF
    echo "    Generated .env.production with secure password."
    echo "    DB password: $DB_PASSWORD (saved in $ENV_FILE)"
else
    echo "[3/5] .env.production already configured, skipping."
fi

# --- 4. Build & Start ---
echo "[4/5] Building and starting services (this takes 3-5 minutes on first run)..."
docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build

# --- 5. Verify ---
echo "[5/5] Verifying deployment..."
echo "    Waiting for services to start..."
sleep 10

# Check health
if curl -sf http://localhost/health > /dev/null 2>&1; then
    echo ""
    echo "=========================================="
    echo "  DEPLOYMENT SUCCESSFUL"
    echo "=========================================="
    echo ""
    echo "  App:     http://$(curl -sf ifconfig.me 2>/dev/null || echo '<your-vps-ip>')"
    echo "  API:     http://$(curl -sf ifconfig.me 2>/dev/null || echo '<your-vps-ip>')/docs"
    echo "  Config:  $ENV_FILE"
    echo ""
    echo "  Useful commands:"
    echo "    cd $APP_DIR"
    echo "    docker compose -f docker-compose.prod.yml --env-file .env.production logs -f"
    echo "    docker compose -f docker-compose.prod.yml --env-file .env.production restart"
    echo "    docker compose -f docker-compose.prod.yml --env-file .env.production down"
    echo ""
else
    echo ""
    echo "  Services are starting... check in 30 seconds:"
    echo "    curl http://localhost/health"
    echo "    docker compose -f docker-compose.prod.yml --env-file .env.production logs -f"
    echo ""
fi
